# Dependabot configuration file
# <https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file>
#
# Each ecosystem is checked on a scheduled interval defined below.  To trigger
# a check manually, go to
#
#   https://github.com/nextstrain/nextstrain.org/network/updates
#
# and look for a "Check for updates" button.  You may need to click around a
# bit first.
---
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/auspice-client/"
    # If you want to run this manually, go to https://github.com/nextstrain/nextstrain.org/network/updates
    # and click "Recent update jobs" then "Check for updates".
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "auspice"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
