# Prevent parent configuration from being applied.
root: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended

settings:
  react:
    version: "16"

ignorePatterns:
  - public/

rules:
  no-case-declarations: off
  no-empty-pattern: off
  no-unused-vars: off
  react/prop-types: off # Remove this override once all props have been typed using PropTypes or TypeScript.

parserOptions:
  sourceType: module
  ecmaVersion: 2022

env:
  browser: true
  es6: true
  node: true
