#!/bin/bash
# Determines commit hashes for the `index-resources.yml` GH Action workflow
#
# Uses the GITHUB_SHA if the workflow was called as a reusable workflow or
# if the workflow was manually run on a branch that is not the default branch.
# Otherwise, returns a JSON array of the unique commit hashes for the
# Nextstrain production and canary Heroku apps.
set -euo pipefail

: "${HEROKU_TOKEN:?The HEROKU_TOKEN environment variable is required.}"
: "${GITHUB_EVENT_NAME:?The GITHUB_EVENT_NAME environment variable is required.}"
: "${GITHUB_REF:?The GITHUB_REF environment variable is required.}"
: "${GITHUB_SHA:?The GITHUB_SHA environment variable is required.}"
: "${IS_WORKFLOW_CALL:?The IS_WORKFLOW_CALL environment variable is required.}"

: "${PROD_APP_NAME:=nextstrain-server}"
: "${CANARY_APP_NAME:=nextstrain-canary}"

main () {
    if [[ "$IS_WORKFLOW_CALL" == true || \
          ("$GITHUB_EVENT_NAME" == 'workflow_dispatch' && "$GITHUB_REF" != 'refs/heads/master') ]]; then
        echo "[\"$GITHUB_SHA\"]"
    else
        fetch_prod_and_canary_refs
    fi
}

fetch_prod_and_canary_refs() {
    >&2 echo "Fetching refs from prod (${PROD_APP_NAME}) and canary (${CANARY_APP_NAME}) apps"

    local prod_commit
    local canary_commit

    prod_commit=$(get_heroku_slug_commit "$PROD_APP_NAME")
    >&2 echo "Prod commit ${prod_commit}"

    canary_commit=$(get_heroku_slug_commit "$CANARY_APP_NAME")
    >&2 echo "Canary commit ${canary_commit}"

    jq -c --null-input \
        --arg PROD_COMMIT "$prod_commit" \
        --arg CANARY_COMMIT "$canary_commit" \
        '[ $PROD_COMMIT, $CANARY_COMMIT ] | unique'
}

get_heroku_slug_commit() {
    local app_name="$1"
    local slug_id commit_hash
    slug_id=$(curl https://api.heroku.com/apps/"$app_name"/releases \
                --fail --silent --show-error \
                -H "Accept: application/vnd.heroku+json; version=3" \
                -H "Authorization: Bearer $HEROKU_TOKEN" \
                -H "Range: version ..; order=desc,max=1" \
                | jq -r '.[0].slug.id')

    commit_hash=$(curl https://api.heroku.com/apps/"$app_name"/slugs/"$slug_id" \
                    --fail --silent --show-error \
                    -H "Accept: application/vnd.heroku+json; version=3" \
                    -H "Authorization: Bearer $HEROKU_TOKEN" \
                    | jq -r '.commit')

    echo "$commit_hash"
}


main "$@"
