name: index resources

on:
  # Run at ~4am UTC time which is (± an hour) 4am UK, 5am Switzerland, midnight
  # US east coast, 9pm US west coast so that for most users (and most
  # developers) the index regenerates overnight
  schedule:
    - cron: '0 4 * * *'

  # Manually triggered using GitHub's UI
  workflow_dispatch:

  workflow_call:

defaults:
  run:
    # This is the same as GitHub Action's `bash` keyword as of 20 June 2023:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
    #
    # Completely spelling it out here so that GitHub can't change it out from under us
    # and we don't have to refer to the docs to know the expected behavior.
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  build-ref-matrix:
    runs-on: ubuntu-latest
    outputs:
      ref-matrix: ${{ steps.ref-matrix.outputs.ref-matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - id: ref-matrix
        name: Create ref matrix
        env:
          HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN_READ_PROTECTED }}
        run: |
          if [[ "$GITHUB_EVENT_NAME" == 'workflow_call' || \
               ("$GITHUB_EVENT_NAME" == 'workflow_dispatch' && "$GITHUB_REF" != 'refs/heads/master') ]]; then
            # This the commit SHA that triggered the workflow.
            # For the workflow_call, this is in the context of the calling workflow.
            # <https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows>
            ref_matrix=$(jq -c --null-input '[ env.GITHUB_SHA ]')
          else
            ref_matrix=$(./scripts/get-resource-index-ref-matrix)
          fi

          echo "ref-matrix=$ref_matrix" | tee -a "$GITHUB_OUTPUT"

  rebuild-index:
    needs: [build-ref-matrix]
    strategy:
      matrix:
        ref: ${{ fromJson(needs.build-ref-matrix.outputs.ref-matrix) }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - run: npm ci
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::827581582529:role/GitHubActionsRoleResourceIndexer
      - name: Rebuild the index
        run: |
          node resourceIndexer/main.js \
            --gzip --output resources.json.gz \
            --resourceTypes dataset --collections core staging
      - name: Extract RESOURCE_CONFIG from config module
        run: |
          # This conditional is to continue to support servers that are still
          # using versions of this code that do not include the get-resource-index
          # script. We can remove it once all the servers have been updated.
          #   -Jover, 01 May 2024
          if [[ -f ".scripts/get-resource-index.js" ]]; then
            resource_index=$(node scripts/get-resource-index.js)
          else
            resource_index=$(jq -r '.RESOURCE_INDEX' ./env/production/config.json)
          fi

          echo "RESOURCE_INDEX=$resource_index" | tee -a "$GITHUB_ENV"

      - name: Upload the new index, overwriting the existing index
        if: ${{ startsWith(env.RESOURCE_INDEX, 's3://') }}
        run: |
          aws s3 cp resources.json.gz "$RESOURCE_INDEX"
