name: index resources

on:
  # Run at ~4am UTC time which is (± an hour) 4am UK, 5am Switzerland, midnight
  # US east coast, 9pm US west coast so that for most users (and most
  # developers) the index regenerates overnight
  schedule:
    - cron: '0 4 * * *'

  # Manually triggered using GitHub's UI
  workflow_dispatch:

  workflow_call:

jobs:
  rebuild-index:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          # This the commit SHA that triggered the workflow.
          # For the workflow_call, this is in the context of the calling workflow.
          # <https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows>
          ref: ${{ github.sha }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
      - run: npm ci
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::827581582529:role/GitHubActionsRoleResourceIndexer
      - name: Rebuild the index
        run: |
          node resourceIndexer/main.js \
            --gzip --output resources.json.gz \
            --resourceTypes dataset --collections core staging
      - name: Extract RESOURCE_CONFIG from config module
        run: |
          # This conditional is to continue to support servers that are still
          # using versions of this code that do not include the get-resource-index
          # script. We can remove it once all the servers have been updated.
          #   -Jover, 01 May 2024
          if [[ -f ".scripts/get-resource-index.js" ]]; then
            resource_index=$(node scripts/get-resource-index.js)
          else
            resource_index=$(jq -r '.RESOURCE_INDEX' ./env/production/config.json)
          fi

          echo "RESOURCE_INDEX=$resource_index" | tee -a "$GITHUB_ENV"

      - name: Upload the new index, overwriting the existing index
        if: ${{ startsWith(env.RESOURCE_INDEX, 's3://') }}
        run: |
          aws s3 cp resources.json.gz "$RESOURCE_INDEX"
